backend:
  name: github
  repo: fizal619/nideca_website
  branch: master
  site_domain: nideca.netlify.app

local_backend: true

media_folder: "images/uploads"

collections:
  - name: products # Used in routes, e.g., /admin/collections/blog
    label: Product # Used in the UI
    folder: "_products/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{ slug }}" # Filename template, e.g., YYYY-MM-DD-title.md
    description: All fields are required except Images and Description.
    fields: # The fields for each document, usually in front matter
      - {label: Name, name: name, widget: string, required: true}
      - {label: "Product Code", name: title, widget: string, required: true}
      - label: "Product Tags/Categories"
        name: tags
        widget: relation
        collection: tags
        value_field: title
        multiple: true
        search_fields: [ "name" ]
        display_fields: [ "name" ]
        required: true
      - label: Images
        widget: image
        name: images
        default: /images/250.png
      - {label: "Description", name: "description", widget: "markdown"}

  - name: tags
    label: Tag/Category
    folder: "_tags/"
    create: true
    slug: "{{ slug }}"
    description: Both values here should be unique. Please follow the example pattern for URL Shortname.
    fields:
      - label: URL Shortname
        description: eg. bathroom-tiles for "Bathroom Tiles"
        name: title
        required: true
      - label: Display Name
        name: name
        required: true

