backend:
  name: github
  repo: fizal619/nideca_website
  branch: master
  site_domain: nideca.netlify.app

media_folder: "images/uploads"

collections:
  - name: "product" # Used in routes, e.g., /admin/collections/blog
    label: "Product" # Used in the UI
    folder: "_products/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{ code }}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Product Code", name: "code", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Description", name: "description", widget: "markdown"}