name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

        # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path:  vendor/bundle/ruby/2.7.1/gems
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Deal with deps
        run: |-
          echo "DEBUG >"
          sudo apt-get install libmagickwand-dev
          cat /etc/ImageMagick-6/policy.xml | sed 's/none/read,write/g' | sudo tee /etc/ImageMagick-6/policy.xml

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - run: |-
          bundle install --jobs 4 --retry 3

      - run: bundle exec jekyll build

      - run: ls

      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          EMAIL: fizal.sarif@gmail.com
          GH_TOKEN: ${{ github.token }}
          BUILD_DIR: _site
          JEKYLL_SITE: YES


